### ISSUE TITLE
Non funcational local documention server

### ISSUE THREAD

**Issue by th31nitiate** [kapicorp/kapitan#1030]
**Describe the bug/feature**
The docker container seems to have issue regarding how mkdocs is configured to be used with kapitan. This is mainly for local development.

**To Reproduce**
Run `make local_server_documention`. This causes an error. One which that that the `pwd` command is in all capitalized. This should not be the situation as Linux is case sensitive.

The second is the mode that `mkdocs` is run in. As it is configured to run ins strict mode. It is not possible  launch the server. Looking at the docs the server does not seem to be a way configure this using environment variables. Unless we use cli arguments ?

The cli parameter of interest would be `dev_addr`.  I am not entirely sure how important the `mkdocs.yml` config file is. If it is relevant to production deployments. 

**Expected behavior**
upon running the command `make local_server_documention` the site should be viewable at `localhost:8000`

**Additional context**
I am more than willing to submit a pull request to fix the issue.

**Comment by MatteoVoges** [comment]
Yeah, this is a known issue. My fix was to remove the `strict: true` at the beginning of `mkdocs.yml`.
Hope this helps...

**Comment by th31nitiate** [comment]
Yes, I just set it to false also but I was wondering if it should be patched in the main branch. 

How about the issue with the `PWD`  variable. Did you experience this aswell ?

**Comment by MatteoVoges** [comment]
The PR is merged now, so the instructions to start the local docs, should be fine. Let me know, if there is still something to do here!
