### ISSUE TITLE
Pull secrets from Hashicorp Vault

### ISSUE THREAD

**Issue by DWSR** [kapicorp/kapitan#105]
As a Vault user, I would like Kapitan to be able to pull information from Hashicorp Vault so that I can have a single authority on secrets in my organization.

**Acceptance Criteria:**
* Supports both v1 and v2 [KV backends](https://www.vaultproject.io/docs/secrets/kv/index.html) including the ability to specify a version of a value where appropriate.
* Inherits or detects Vault information from the environment/other mechanisms (i.e. reads the token from `~/.vault-token`, uses `VAULT_ADDR`, etc.)
* Has the ability to explicitly specify Vault information to override inherited or detected configurations.
* Supports basic CRUD operations on an arbitrary secret backend
* Supports, at minimum, the `userpass`, `token`,  and `cert` authentication mechanisms.

**Comment by DavidJeche** [comment]
This looks interesting but i would suggest the best thing to do here might be to generate config i.e for terraform, generate the terraform with consul template variable in place where secret should be. 

When you run a deployment set your CI system to run consul template on the compiled file. This means you can keep the manifests,  secrets and environments independent of kapitan tool.

**Comment by DWSR** [comment]
So if I understand this correctly, you're suggesting templating out a consul-template file with Jinja (because I doubt you can get this to work in JSonnet)?

**Comment by DavidJeche** [comment]
I am not that familiar with Jsonnet and I am currently learning as a configuration language. I am not even sure how to manage dependencies with in terraform like how I reference an alternative resource or take output from a resource like IP address. 

The main suggestion was to add string tags something like this should work:
` {
  locations: {
    'MyDataCenters': {
      description: "{{ range datacenters }}
{{ . }}{{ end }}",
   },
  },
}`

It will output the following:

`{
  "locations": {
    "MyDataCenters": {
      "description": "{{ range datacenters }}\n{{ . }}{{ end }}"
    }
  }
}`

What you can do is in the deployment environment run consul template in the step before the deployment. This will create new file or temp file that have the secrets. The files are then deleted after the apply. You still have the original compiled files for reference of what been applied. 

I would recommend not to go too crazy with it. There will most likely be clashies somewhere but its a workable solutions until the vault integration is added. I am fairly certain it would be there before version one.

**Comment by calvinmorrow** [comment]
I started looking into whether Vault KV support was something I could add, but currently a bit tripped up on how to handle the `RefBackend.__getitem__` method.  

Kapitan's compile support seems opinionated on being able to know in advance whether a secret exists without knowing its (unencrypted) data.  In the case of Vault that isn't true unless you connect to Vault and check.  All the other backends have Yaml files for loading in the secret `from_path` method with path and hash data.

Can an author give some guidance on how they think that support should be structured?

**Comment by daminisatya** [comment]
Is someone working on this? I would like to investigate it. 

@uberspot @ramaro

**Comment by uberspot** [comment]
Not as far as I know. Feel free to work on it. :)

**Comment by vaibhavk** [comment]
Hello @daminisatya I'm investigating about it too, would you mind I collaborate with you?

**Comment by ramaro** [comment]
@calvinmorrow I'm sorry, but I somehow missed your update!
I think Vault could work out of the box with Kapitan's secret model if using the Transit Secrets Engine. Similar approaches have been developed for both `awskms` and `gkms`.

Supporting  scenarios other that this will likely require some minimal adjustments to Kapitan Secrets/Refs.

How are you planning to work on this? (also for @vaibhavk )
