### ISSUE TITLE
[docs]: kapitan compile help  , click to expand output is mangled 

### ISSUE THREAD

**Issue by ecerulm** [kapicorp/kapitan#1093]
### Description of the documentation issue

On the page https://kapitan.dev/pages/commands/kapitan_compile/#help, when you click on click to expand output the text is not rendered right

![Pasted_Image_2023-11-15__14_36](https://github.com/kapicorp/kapitan/assets/58676/947a2bd9-c05e-4c1c-acf0-461aaae5bb7b)

**Comment by MatteoVoges** [comment]
Thank you for the report!
