### ISSUE TITLE
[bug]: Performance regression in v0.33.1

### ISSUE THREAD

**Issue by sodul** [kapicorp/kapitan#1174]
### Description of the bug

`kapicorp/kapitan:0.33.1` is significantly slower than 0.33.0 when compiling.

### Steps to reproduce

```bash
> docker run --rm --user=0 -v "$(pwd)/kapitan:/src" 'kapicorp/kapitan:0.33.1' compile
```
This completes in 6m while it takes 30s or less with v0.33.0.
```


### What happened?

We upgraded to 0.33.1. Nothing else is different.


### Additional context

Unfortunately we cannot share our source files but we assume that this issue is common enough and should be easy to reproduce.

Note the versions fields for kapitan and Python below are out of date so I put 'master'.

### Version (kapitan)

master

### Version (kapitan)

I use kapitan directly (pip, docker)

### Python virtual environment

- [X] pyenv
- [ ] venv
- [ ] no environment

### OS information

macOS 14, M1 CPU

### Relevant log output

_No response_

**Comment by ademariag** [comment]
Hello @sodul, I have just release [v0.34.0-rc.0](https://github.com/kapicorp/kapitan/releases/tag/v0.34.0-rc.0) which should address some performance issues and also provide more information about the speed of kapitan. could you please check again with this version?

**Comment by sodul** [comment]
It seems that this RC has fixed the speed issue. Thanks!
