### ISSUE TITLE
[bug]: KapitanInputTypeKadetConfig inherits prune from KapitanInputTypeBaseConfig

### ISSUE THREAD

**Issue by JordanLloydHall** [kapicorp/kapitan#1257]
### Description of the bug

After adding Pydantic types for Inventory, the assumption was introduced that Kadet Input in Kapitan should always prune objects before serialization to a file. 
However, there are many cases for which this is not the case, such as [Flux's ImageRepository](https://fluxcd.io/flux/components/image/imagerepositories/#:~:text=To%20grant%20access%20to%20all%20namespaces%2C%20an%20empty%20matchLabels%20can%20be%20set%3A), where it is expected that the object is empty.

### Steps to reproduce

```bash
1. Use Kadet as input for an object with an empty dictionary as a value to a key.
2. Run `kapitan compile`.
3. See that neither the key nor value appears in the compiled directory.
```

### What happened?

The key (with an empty dict as a value) should be in the compiled directory.

### Additional context

This was introduced in [PR #1234](https://github.com/kapicorp/kapitan/pull/1234). Specifically in [line 36 of kapitan/inventory/model/input_types.py](https://github.com/kapicorp/kapitan/blob/master/kapitan/inventory/model/input_types.py#L36).

### Version (kapitan)

master

### Version (kapitan)

I use kapitan directly (pip, docker)

### Python virtual environment

- [ ] pyenv
- [ ] venv
- [ ] no environment

**Comment by ademariag** [comment]
Thank you @JordanLloydHall , this was unintentional caused by the migration. after testing I will release a new fix version

**Comment by JordanLloydHall** [comment]
> Thank you @JordanLloydHall , this was unintentional caused by the migration. after testing I will release a new fix version

Thank you for your great work on this project!
