### ISSUE TITLE
Expand on kapitan init

### ISSUE THREAD

**Issue by uberspot** [kapicorp/kapitan#215]
Expand on the work done https://github.com/deepmind/kapitan/pull/213 
and add functionality to:

 - generate parameterizable target files
 - generate parameterizable class files
 - generate parameterizable components (jinja2, kadet, jsonnet)

**Comment by vaibhavk** [comment]
parameterizable here refers to the command-line parameters support?

**Comment by uberspot** [comment]
I think the concept here was to try and make `kapitan init` generate example target/class/component files based on some parameters that a user inputs. 
Something like `kapitan init --target-name <a new target name>` and it would generate the correctly named file for the user. And the generation would handle the `kapitan.compile` parameters, depending if the user wants jinja2, jsonnet or kadet.
This would probably simplify kapitan usage even more.

**Comment by vaibhavk** [comment]
This makes more sense to me now, thanks

**Comment by MatteoVoges** [comment]
Closing this as the PR #265 got closed too. You could just reopen the PR
