### ISSUE TITLE
Ability to specify custom target path

### ISSUE THREAD

**Issue by afoninsky** [kapicorp/kapitan#275]
I’ve found that I need to share inventory targets and secrets between my customers keeping the rest of configuration in common maintainable repository. I can specify `--secrets-path` but it’s not possible to specify `--target-path` (`--inventory-path` does not fit as it includes classes too)

**Feature request**
(minimum) Add flag `--target-path[s?]` which points to custom directory with targets
(maximum) Add ability to specify pathes using configuration file, so users will be able to maintain own repository structures

**Comment by supra08** [comment]
@uberspot I would like to work on this issue.

**Comment by MatteoVoges** [comment]
As a workaround you could change the `nodes_uri` in your `reclass-config.yml` file. This file has to be in the inventory_path which you specify with `--inventory-path` or default `inventory`. Please let me know, if there are any further questions.
