### ISSUE TITLE
Reading values from environment variables

### ISSUE THREAD

**Issue by xydinesh** [kapicorp/kapitan#294]
**Describe the bug/feature**

I like to populate jsonnet template or yaml parameters using an environment variable before running `kapitan compile`.  We are using environment variable `CI_PIPELINE_ID` to create docker images and want to use this value with the image for deployment. For example,

```
image: xydinesh/testimage:${CI_PIPELINE_ID}
```

Is there a way to do this with jsonnet templates ? Or do I have to generate a yaml with this new image before running `kapitan compile`

```
local kap = import "lib/kapitan.libjsonnet";
local inv = kap.inventory();
local replicas = inv.parameters.nginx.replicas;
local image = inv.parameters.nginx.image;
local namespace = inv.parameters.namespace;
```

Thanks !

**Comment by uberspot** [comment]
Related to https://github.com/deepmind/kapitan/issues/211 
Implementation should be the same/similar for both issues.
It's not a fully recommended practice to have configuration as environment vs as code, but the functionality makes sense so this feature could be implemented. :) 
An example implementation would parse the inventory after reclass and check for $strings. 
Env vars would have to be in that format and without curly braces {}  to avoid reclass interpreting them as inventory variables.

**Comment by xydinesh** [comment]
Thanks ! If I can access `CI_PIPELINE_ID` environment variable to create correct docker image tag for deployment, I wouldn't worry about the syntax ({}). For now, I will use a python script to create new yaml file with this value.

**Comment by ramaro** [comment]
The new Ref proposal https://github.com/deepmind/kapitan/pull/298 could solve this problem for you with the support for updating refs via the command line. You could write/update refs with the value of your envs vars.

**Comment by frittentheke** [comment]
@uberspot the Docker image ID which is known just before Kapitan is run is exactly what brought me here. Being able to consume environment variables would be awesome ... just please make Kapitan require them if referenced and if not just fail  ...

**Comment by zoek1** [comment]
hey @uberspot could i work on this as first good issue?

**Comment by uberspot** [comment]
Hello, :) you can always just start work on an issue without confirmation. We don't strictly assign open issues to people.

**Comment by zoek1** [comment]
Thanks, i would like participate on the GSoC with the Kapitan so i want tackle this to familiarize. :smiley:

**Comment by AlphaRoy14** [comment]
Hi! I was wondering if this issue still needs solving. As mentioned above by @ramaro, we can refer to environment variables by writing a ref. Eg. `echo $ENV_VAR | kapitan refs --write plain:my/ENV_VAR -f -` and then refer to it from the targets. Eg. `image: ?{plain:my/ENV_VAR}`. Maybe we can update the docs instead and explain how to use environment variables in targets?

**Comment by uberspot** [comment]
A doc update here would probably be more appropriate. Refs are equally flexible and would cover most users.

**Comment by ramaro** [comment]
Agree!

**Comment by farvour** [comment]
I opened up a PR to make a feature for automatically using the environment. It avoids you from having to do strange workarounds and allows the values to be updated in-real-time during reveal/render phase without requiring a recompile like the plainRef does. Since base64 refs use a hash, a change to the value before reveal would violate the hash constraint.

I feel like this solves a happy medium where a secret/ref is somewhere in between a plain and a base64, and one wants to be able to change the value revealed on the fly, say, during a deploy without having to recompile (which would ruin a deterministic/immutable manifest compilation).

It's still sorta WIP this instant but would like to get some test cases going.

**Comment by uberspot** [comment]
Done in https://github.com/kapicorp/kapitan/pull/530
