### ISSUE TITLE
Base64 encoded secrets are not revealed

### ISSUE THREAD

**Issue by taharah** [kapicorp/kapitan#341]
**Describe the bug/feature**
When using an encrypted value via Kapitan secrets to create a Kubernetes secret, if the encrypted value is nested within a document, then the output will include the base64 encoded reference to the secret.

**To Reproduce**
1. Encrypt a value with Kapitan secrets
2. Create a jsonnet manifest that base64 encodes a document that has the value embedded and compile.
3. Decode the base64 string and you will find the embedded reference to the Kapitan secret.

**Expected behavior**
I would expect the output to include the decrypted value.

**Screenshots**
If applicable, add screenshots to help explain your problem/idea.

** If it's a bug (please complete the following information):**
 - `python --version`: 3.7.4
 - `pip3 --version`: 19.2.2
 - `Are you using pyenv or virtualenv?` virtualenv

**Additional context**

**Comment by ramaro** [comment]
@taharah running base64 in jsonnet on a secret won't work because it will base64 the reference and not the content as you say.

I suggest you remove the base64 function call from jsonnet and create your secret instead with:
`$ kapitan secrets --write gpg:my/secret -f value.txt --base64`.

The `--base64` flag here will encode the content before encrypting it, which will have the desired effect.

I believe this is what is happening, but it would be great if you can provide some snippets.

**Comment by taharah** [comment]
I have used the flag `--base64` previously for individual values that I am trying to protect; however, the issue is when I need to only protect a small portion of a configuration file, e.g., an API key. In this case, I would need to encrypt the entire file, which makes updating and maintaining the file far more difficult. Additionally, since Kapitan does not currently use envelope encryption, at least for KMS, files are limited in size to 4 KB.

**Comment by uberspot** [comment]
How about templating the configuration file as well? Then you can just add the api key you mention as a secret reference in that template.

**Comment by ramaro** [comment]
Sorry, can you share some snippets to help understand your problem clearly?

**Comment by taharah** [comment]
For example, if I have something like the following in my inventory:

```yaml
parameters:
  alertmanager:
    configuration:
      resolve_timeout: 5m
      opsgenie_api_key: ${gpg:targets/${target_name}/opsgenie/api.key}
```

Then try to create a secret file from the entire configuration blob like shown below:

```jsonnet
{
  secret: kube.Secret(name) {
    data: {
      config.yml: std.base64(
        std.manifestYamlDoc(inv.parameters.alertmanager.configuration)
      ),
    },
  },
}
```

When you run `kapitan compile --reveal`, the output file has the string `${gpg:targets/${target_name}/opsgenie/api.key}` in the base64 encoded string and not the decrypted value.

**Comment by ramaro** [comment]
I'd recommend you use a ConfigMap in that case. It should work as it doesn't use `std.base64()`

**Comment by taharah** [comment]
@ramaro I opened a PR that resolves the issue since using a ConfigMap is not always possible especially when using operators that expect the configuration to be a secret.

**Comment by calvinmorrow** [comment]
Chiming in here with my own experiences -

With the new Helm input type this same issue comes up a bit more often.  Several Helm charts embed configuration into k8s secrets (I'm looking at Grafana Lab's Loki chart atm, but several more do as well).  They're often for generating a configuration file with settings and embedded S3 or GCS keys that all get slurped by a Golang process.

At the moment that means the secret ref is encoded into the output (which of course doesn't work) and no easy workarounds (other than managing the secret myself outside of Kapitan)

**Comment by jperville** [comment]
As a workaround, it is possible to rewrite a secret base64-encoded `.data` into a plain text  `.stringData`.

For example with kube-prometheus, the alertmanager configuration is encoded in a secret, which contains different API keys (which we want to declare as secret in Kapitan inventory).

Here is how my `prometheus/main.jsonnet` file looks like:

```jsonnet
local kp =
  (import 'kube-prometheus/kube-prometheus.libsonnet') +
  (import 'kube-prometheus/kube-prometheus-kubeadm.libsonnet') +
  {
     ...
  };

// kapitan cannot replace secret refs in base64-encoded data (https://github.com/deepmind/kapitan/issues/341)
// as a workaround, rewrite the alert-manager secret base64 data into plain-text stringData
local decoded_alertmanager_secret = {
  local secret = kp.alertmanager['secret'],
  local encoded = secret.data,

  local decoded = {
    [key]: std.base64Decode(encoded[key]) for key in std.objectFields(encoded)
  },

  'alertmanager-secret': secret {
    stringData: decoded,
    data: {},
  }
};

{ ['00namespace-' + name]: kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus) } +
{ ['0prometheus-operator-' + name]: kp.prometheusOperator[name] for name in std.objectFields(kp.prometheusOperator) } +
{ ['node-exporter-' + name]: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['kube-state-metrics-' + name]: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
{ ['alertmanager-' + name]: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['prometheus-' + name]: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
{ ['grafana-' + name]: kp.grafana[name] for name in std.objectFields(kp.grafana) } +
{ [name + '-ingress']: kp.ingress[name] for name in std.objectFields(kp.ingress) } +
{ [name + '-ingress-secret']: kp.ingress_secrets[name] for name in std.objectFields(kp.ingress_secrets) } +
decoded_alertmanager_secret
```

**Comment by ademariag** [comment]
Another solution is to use Kapitan (generators?) to create the secrets, and tell helm not to create it. For instance:

## Disable the creation of the secret (must be supported by the chart)
```
    helm_values:
      secret:
        create: false
 ````
 
## Generate the secret with Kapitan
```
  generators:
    kubernetes:
      secrets:
        my_secret:
          type: kubernetes.io/tls
          data:
            tls.crt:
              value: ?{plain:templates/snakeoil-cert-pem}
            tls.key:
              value: ?{plain:templates/snakeoil-cert-key}
  ```


There are multiple solutions already provided, and this will be solved for good by https://github.com/kapicorp/kapitan/pull/880.
