### ISSUE TITLE
Query: are there any plans to support Azure vaults ?

### ISSUE THREAD

**Issue by anirban1c** [kapicorp/kapitan#366]
love kapitan, any plans to support azure vaults ?

**Comment by ramaro** [comment]
Thanks! No plans at the moment but we are always happy to help and review PRs 😄

**Comment by anirban1c** [comment]
sure, will do

**Comment by anirban1c** [comment]
would it be possible to get an invite for slack channel ? have been going through the code and have a few questions about what az vault features  to use/implement, ask some silly questions to check if I understood the concepts, thanks

**Comment by ramaro** [comment]
@anirban1c does https://slack.k8s.io/ work for you?

**Comment by anirban1c** [comment]
yes, thanks @ramaro , got it

**Comment by uberspot** [comment]
Done by https://github.com/kapicorp/kapitan/pull/590
