### ISSUE TITLE
Add support for helm bindings in OSX

### ISSUE THREAD

**Issue by uberspot** [kapicorp/kapitan#368]
As a followup from https://github.com/deepmind/kapitan/pull/359
This ticket is to track the work for OSX helm bindings + testing them on Travis.

cc @yoshi-1224

**Comment by ademariag** [comment]
This would be very cool to have.... Any updates?

**Comment by yoshi-1224** [comment]
@uberspot Happy to help

**Comment by uberspot** [comment]
Go for it :) happy to review any PRs when you have em.

**Comment by yoshi-1224** [comment]
@uberspot
So any suggestions as to what we should go with?

**Comment by uberspot** [comment]
Yes, sorry I had to think a bit on the possible solutions. 
Dynamically fetching the .so file when kapitan runs might be a bit "dodgy". It's very rare that templating tools download shared libraries dynamically from the internet. And that might be also hard to do in environments that have restricted access to the internet.

I'd like to try and keep the steps of building the .so library in travis (osx) independent from the packaging steps to simplify maintenance.

So I'd suggest as a first step on this, let's focus on creating a travis job/pipeline that would build the osx bindings on travis (osx) and just release them to Github Releases. This should only happen on the master branch, same way we currently release to pypi and GH. 

A second step after that would be actually packaging the bindings to our pypi release. 
That could either be a manual step a maintainer does (less preferred) or if possible we could modify the existing travis job to wait (on the master branch) until the bindings are available (https://docs.travis-ci.com/user/common-build-problems/#my-builds-are-timing-out  `travis_wait` referenced here).

That is a less elegant solution so I'd leave that as a further step and focus on first building and releasing the bindings on travis. :)
