### ISSUE TITLE
Remote Inventory Federation

### ISSUE THREAD

**Issue by uberspot** [kapicorp/kapitan#436]
New Feature:
Inventory segments can be fetched from remote locations (https/git) allowing users to combine different inventories from different sources.

Fetching of the inventory has to happen before compiling the inventory with reclass as a separate/initial step.
What is still to be defined is how users would declare their remote inventories  (maybe in .kapitan ?)  and where those files will be saved locally. Putting that config in the inventory makes parsing it before reclass cumbersome so ideally it would be outside of it. 

Along with the feature tests should be added that fetch remote inventories (from our github?) and documentation updated.

Any further input/ideas to this is welcome.

**Comment by isaeef** [comment]
@uberspot  is this still open

**Comment by adrianchifor** [comment]
> @uberspot is this still open

Yes, this is a task dedicated to Google Summer of Code participants.
