### ISSUE TITLE
Search for multiple class & secret paths

### ISSUE THREAD

**Issue by arnisoph** [kapicorp/kapitan#50]
Feature request as discussed in #kapitan.

## Use Case

We have multiple teams (dev/ops/devops) and one infrastructure team. All of them have dedicated/own Git repositories and CI/CD pipelines to rollout applications on Kubernetes with manifests compile by kapitan. To prevent redundant data in classes we (infrastructure team) want to provide a central *CMDB* repository that contains shared (reclass) (inventory) classes and secrets. 
Git-subtree is used to maintain a local copy of the global/shared CMDB Git repository. 

This leads to classes/secrets that are distributed in multiple directories:

```
$ tree
.
`-- deploy/
    |-- cmdb/
    |   |-- classes/
    |   |   `-- kubernetes/
    |   |       |-- clusters.yml
    |   |       `-- namespaces.yml
    |   `-- secrets/
    |       |-- deploy-key
    |       `-- registry-readonly-key
    `-- kapitan/
        |-- inventory/
        |   |-- classes/
        |   |   `-- abc.yml
        |   `-- targets/
        |       `-- mytarget.yml
        `-- secrets/
            `-- eu-central-1/
                `-- monitoring/
                    `-- oidc_key
```

## Feature Request

We need to tell kapitan to search for multiple ``classes`` directories and ``secrets`` directories.

Example:

```
$ cd deploy/kapitan/
$ kapitan compile \
  --class-search-path "classes/:../cmdb/classes/" \
  --secrets-search-path "secrets/:../cmdb/secrets/"
```

This might obsoletes/collides --search-path (?) and --secrets-path.

**Comment by adrianchifor** [comment]
Thanks for the request. I'll discuss with @ramaro next week and I'll link a PR once we get the ball rolling.

**Comment by vaibhavk** [comment]
In kapitan currently we have ```--secrets-path``` for ```compile``` which only searches for one directory for searching secrets, does this refer to adding more than one directory for that?

**Comment by vaibhavk** [comment]
Wouldn't making ```--secret-search``` search more than one directory  be a solution to this? or do we need a separate command for that?

**Comment by MatteoVoges** [comment]
If you still want this feature the [external inventory](https://kapitan.dev/pages/input_types/external/) (`input_type:` `external`) is the right choice.
