### ISSUE TITLE
Enable Setting `KubeVersion` for Helm Template

### ISSUE THREAD

**Issue by srueg** [kapicorp/kapitan#543]
**Describe the bug/feature**
When rendering a Helm chart, the used kube version is fixed to `v1.9`. This leads to issues if this version is used in Helm charts (as it is in [cert-manager](https://github.com/jetstack/cert-manager/blob/f0231cc5d5a7f74fa0d77395546cef2cd0b80efd/deploy/charts/cert-manager/templates/webhook-mutating-webhook.yaml#L29) for example).

**To Reproduce**
1. Use an input type `helm`
2. Use the `{{ .Capabilities.KubeVersion.GitVersion }}` variable in the chart
3. See fixed version

**Expected behavior**
I'd like to have an option to override this default version, ideally via the inventory.

** If it's a bug (please complete the following information):**
 - `python --version`: `Python 3.8.3`
 - `pip3 --version`: `pip 20.0.2`
 - `Are you using pyenv or virtualenv?` virtualenv

**Additional context**
The fixed version is set [here](https://github.com/deepmind/kapitan/blob/master/kapitan/inputs/helm/template.go#L207) and defined [here](https://github.com/helm/helm/blob/release-2.14/pkg/chartutil/capabilities.go#L31).

**Comment by ramaro** [comment]
Fixed in #671
