### ISSUE TITLE
No standalone binary for 0.29.5

### ISSUE THREAD

**Issue by drzero42** [kapicorp/kapitan#734]
There does not appear to be a standalone binary asset attached to the 0.29.5 release.
The documentation still states that this is one way to install Kapitan.
Either the binary should be added to the release, or the documentation should be updated :)

**Comment by adrianchifor** [comment]
Hey, the auto-build and attach for the binary is in travis and it's not currently working. We will dedicate some time to get it back on track or move to github actions completely. For now I've built the binary for the latest tag and attached it manually, or you can build your own with `make build_binary` from the root folder.

**Comment by 617m4rc** [comment]
Will the standalone binary still be available for future releases? Unfortunately, it is also missing for 0.30.rc0 and 0.30.rc1 and we are wondering whether we should switch over to a Docker-based approach.
