### ISSUE TITLE
Print inventory render time on compile

### ISSUE THREAD

**Issue by ramaro** [kapicorp/kapitan#745]
As the inventory can take some time to render, we should add the inventory timing together target compile times. 

Something like this:

```
$ kapitan compile
Rendered inventory (1.00s)
Compiled ride-the-lightning (0.54s)
Compiled the-four-horsemen (1.13s)
Compiled hit-the-lights (1.28s)
...
```

**Comment by opeco17** [comment]
Hi, @ramaro 
I would like to contribute to Kapitan
Could you please assign this task to me?

**Comment by ramaro** [comment]
@opeco17 certainly! Thanks 👍
