### ISSUE TITLE
conditional import of classes

### ISSUE THREAD

**Issue by NatarajanR** [kapicorp/kapitan#807]
**Describe the bug/feature**
Is there a way to conditionally import classes? Also is there a way to do if else condition based on a variable's value?
for example, like below:

```
classes:
- class-a
- ?(is_classb_import_enabled == "enabled"): class-b || class-c    # If is_classb_import_enabled variable's value is enabled, then it will import class b. else it will import class c
```

Am using 0.29.2 version of kapitan

**Comment by 617m4rc** [comment]
Looking for the same. Did you have any success with that?

**Comment by lingwooc** [comment]
@ademariag it's not clear to me where ignore_class_notfound should be set.

**Comment by MatteoVoges** [comment]
I think the work-around provided by @ ademariag should work out. Let us know, if there is still something unclear.
Please check out the inventory queries in reclass. They work like an if-else-statement.
