### ISSUE TITLE
Support unused Ref/Secret finder

### ISSUE THREAD

**Issue by Moep90** [kapicorp/kapitan#853]
As we've iterated multiple times across our kapitan repo structure. It happens that we have unused refs/secrets in our `ref/*` subdir.
Therfore we'd like to get a warning if a secret is existend but not used.

Ideally print a warning on every `compile` or `validate`.

e.g.:

```bash
$ kapitan compile/validate
WARNING! No reference for Secret: "refs/shared/ca/ca_chain"
Rendered inventory (0.18s)
Compiled my-target (6.78s)
```

**Comment by uberspot** [comment]
Have you tried kapitan lint? Does it do what you need? 
It checks your refs for orphan secrets. https://github.com/kapicorp/kapitan/blob/b02a1d851f5808c31f889a9a103985bc16e54d5c/kapitan/lint.py#L94  
It could potentially be added as a flag in the compile step, but usually you could also run this as a separate CI step.

**Comment by Moep90** [comment]
> Hello :)
> 
> Have you tried kapitan lint? Does it do what you need? It checks your refs for orphan secrets.
> 
> https://github.com/kapicorp/kapitan/blob/b02a1d851f5808c31f889a9a103985bc16e54d5c/kapitan/lint.py#L94
> 
> 
> It could potentially be added as a flag in the compile step, but usually you could also run this as a separate CI step.

No, I honestly never tried that. But it also does not give me intel on secrets
```
$ kapitan lint
[....]
Total yamllint issues found: 367 
[...]
No usage found for the following 36 classes:
[...]
```

```
$ kapitan lint 2>&1 | grep -i -e ref -e sec <-- prints nothing
$ 
```

**Comment by uberspot** [comment]
Try `kapitan lint --search-secrets` and if you have secrets in a different folder than ./refs you also need to pass that in via `--refs-path`

**Comment by Moep90** [comment]
@uberspot 
seams to work, great!

```
$ kapitan lint --search-secrets
[...]
Checking for orphan secrets files...

No usage found for the following 46 secrets files:
[...]
```
