### ISSUE TITLE
Update hvac dept to 1.x

### ISSUE THREAD

**Issue by Moep90** [kapicorp/kapitan#854]
Hvac 1.x got released

[See changes here](https://github.com/hvac/hvac/compare/v0.11.2...v1.0.0)

# :exploding_head:  Breaking Changes
- Legacy MFA: Move mfa authentication method to legacy MFA method. https://github.com/hvac/hvac/pull/883
- Remove deprecated methods. https://github.com/hvac/hvac/pull/868
- Remove redundant code for Python <= 3.5. https://github.com/hvac/hvac/pull/822
- Drop Python 2 and EOL Python 3 versions. https://github.com/hvac/hvac/pull/819

# :notebook: Notes:
- minimum python version is now 3.7

**Comment by MatteoVoges** [comment]
Fixed with #1053
