### ISSUE TITLE
Documentation badly formatted

### ISSUE THREAD

**Issue by RobKenis** [kapicorp/kapitan#879]
**Describe the bug/feature**
When visiting https://kapitan.dev/external_dependencies/#helm-type, the code blocks are badly formatted. This makes it hard to use the documentation

**To Reproduce**

1. Go to https://kapitan.dev/external_dependencies/#helm-type
2. See multiline code blocks formatted as single-line code blocks over multiple lines

**Expected behavior**
Documentation has properly formatted code blocks. When the documenation is served locally, this is formatted as expected

**Screenshots**
<img width="853" alt="image" src="https://user-images.githubusercontent.com/25204819/202720067-699f21d5-babc-464f-9638-a74c6770fca3.png">

**Additional context**
Documentation is formatted properly when serving locally with python 3.10

**Comment by ademariag** [comment]
Duplicate of #865
