### ISSUE TITLE
reference subvars not supported for plain type

### ISSUE THREAD

**Issue by ademariag** [kapicorp/kapitan#899]
## Describe the bug/feature
I made a claim in the documentation that you could use YAML References with the plain type, as in the example:

> ```shell
> gcloud container clusters describe \
>   --project ${TARGET_NAME}-project \
>   gke-cluster --zone europe-west1 --format yaml \
>     | kapitan refs --write plain:clusters/${TARGET_NAME}/cluster -t ${TARGET_NAME} -f -
> ```
> 
> knowing the output of `gcloud` to produce yaml that contain the following values:
> 
> ```yaml
> ...
> name: gke-cluster
> releaseChannel:
>   channel: REGULAR
> selfLink: https://container.googleapis.com/v1/projects/kapicorp/locations/europe-west1/clusters/gke-cluster
> ...
> ```
> 
> I can not reference the link to the cluster in the inventory using:
> 
> ```yaml
> parameters:
>   cluster:
>     name: ?{plain:clusters/${target_name}/cluster@name} 
>     release_channel: ?{plain:clusters/${target_name}/cluster@releaseChannel.channel}
>     link: ?{plain:clusters/${target_name}/cluster@selfLink}
> ```

However this is not correct, because this functionality is not supported with the plain type, or at least not if you do not use the `--reveal` function
Instead, one must use base64 or another backend 

### Create secrets
```
kapitan refs --write plain:plain_example -t dev -f bug.yaml
kapitan refs --write base64:base64_example -t dev -f bug.yaml
```

### Inventory 
```
parameters:
  etag_plain: ?{plain:plain_example@key}
  etag_base64:  ?{base64:base64_example@key}
```
### Template

```
plain = {{ inventory.parameters.etag_plain}}
base64 =  {{ inventory.parameters.etag_base64}}
```

### `kapitan compile --reveal`

```
plain = "value"
base64 = "value"
```

### `kapitan compile --reveal`
```
# This is **wrong**, this should should be "value"
plain = "key: value 
"
# This is expected
base64 = ?{base64:etag_base64@key:7f17dab9}"
```

### `kapitan compile --reveal`
```
plain = "value"
base64 = ?{base64:etag_base64@key:7f17dab9}"
```

**Comment by jkrzemin** [comment]
@ramaro shouldn't it be closed?
