### ISSUE TITLE
Update kapicorp/kapitan:master-ci docker image

### ISSUE THREAD

**Issue by Zeratyl06** [kapicorp/kapitan#934]
Describe the bug/feature
I plan to use the random function in CI (https://kapitan.dev/references/#primary-functions), but the kapicorp/kapitan:master-ci image has an old version of kapitan.

Expected behavior
Docker image kapicorp/kapitan:master-ci contains version 0.31.0 of kapitan.

If it's a bug (please complete the following information):
```
python --version
Python 3.7.12
kapitan --version
0.30.0rc0
```

**Comment by MatteoVoges** [comment]
Thank you for noticing.
Just to make it work: In your version the function was called `randomstr` and did not support other data types than string.

**Comment by Zeratyl06** [comment]
Thank you. Let's roll back the changes to version 0.30. If you have time, please update the docker image.

**Comment by MatteoVoges** [comment]
I think the image `master:ci` was removed a year ago. Please use the 'normal' `latest` image.

**Comment by Zeratyl06** [comment]
This is not possible without rebuilding the docker image. Because the default user is kapitan, and he does not have root rights.

**Comment by Zeratyl06** [comment]
That's what I planned to do. `root` privileges are needed to set up the environment before using kapitan.
